### ISSUE TITLE
How to calculate the actual transport plan?

### ISSUE THREAD

**Issue by angshine** [meyerscetbon/LinearSinkhorn#1]
Hi, thanks for the great work! Unlike the OT-GAN example, I want to use the transport plan in my learning algorithm and directly supervise the transport plan. However, if I use `c_{\theta}(x, y):=-\varepsilon \log \varphi_{\theta}(x)^{T} \varphi_{\theta}(y)` as the cost matrix to calculate the final transport plan, it is hard to converge (the scaling vector `u^*` and `v^*` are calculated with the proposed LinearSinkhorn). Is it the right way to recover the transport plan?

**Comment by meyerscetbon** [comment]
Hello, I'm glad you like our work.
You should directly consider the Sinkhorn iterations with the kernel $\varphi_{\theta}(x)^{T} \varphi_{\theta}(y)$.
The convergence of the Sinkhorn algorithm depends on the regularization $\varespilon$ chosen and the minimum value of the kernel. Therefore you may scale these parameters (the feature map \varphi_{\theta} and the regularization) to obtain fast convergence. 
Moreover, note that the convergence can be obtained only if the coefficients of the kernel matrix are all positive, therefore the embedding should live in the orthant.
